Repository cuboss/captain, pull requests merged in 2022-07, with the labels that each got.

#9 fix readme
  README.md
Labels: kind/documentation

#11 Feature/docker ci
  .github/workflows/docker.yml
  .github/workflows/github-actions-demo.yml
  Dockerfile
  Makefile
  deploy/deploy.yaml
Labels: enhancement

#13 Feature/captain configmap
  deploy/deploy.yaml
Labels: kind/bug

#15 Feature/docs
  .github/workflows/docker.yml
  .github/workflows/github-actions-demo.yml
  README.md
  docs/guide/development.md
  docs/guide/quick-start.md
Labels: documentation, kind/documentation
