Repository cuboss/captain, pull requests merged in 2022-10, with the labels that each got.

#25 fix lint and docs
  deploy/deploy.yaml
  docs/multi-clusters.md
  pkg/controller/cluster/cluster_controller.go
  pkg/server/dispatch/dispatch.go
  pkg/server/request/requestinfo.go
  pkg/server/request/requestinfo_test.go
Labels: kind/documentation, bugfix

#27 * add multi cluster scope resources caps interface
  docs/multi-clusters.md
  pkg/bussiness/kube-resources/alpha1/clusterrole/multi_cluster_clusterrole.go
  pkg/bussiness/kube-resources/alpha1/clusterrolebinding/multi_cluster_clusterrolebinding.go
  pkg/bussiness/kube-resources/alpha1/configmap/multi_cluster_configmap.go
  pkg/bussiness/kube-resources/alpha1/cronjob/multi_cluster_cronjob.go
  pkg/bussiness/kube-resources/alpha1/daemonset/multi_cluster_daemonset.go
  pkg/bussiness/kube-resources/alpha1/deployment/multi_cluster_deployment.go
  pkg/bussiness/kube-resources/alpha1/ingress/multi_cluster_ingress.go
  pkg/bussiness/kube-resources/alpha1/interface.go
  pkg/bussiness/kube-resources/alpha1/job/multi_cluster_job.go
  pkg/bussiness/kube-resources/alpha1/namespace/multi_cluster_namespace.go
  pkg/bussiness/kube-resources/alpha1/networkpolicy/multi_cluster_networkpolicy.go
  pkg/bussiness/kube-resources/alpha1/networkpolicy/networkpolicy.go
  pkg/bussiness/kube-resources/alpha1/node/multi_cluster_node.go
  pkg/bussiness/kube-resources/alpha1/persistentvolume/multi_cluster_persistentvolume.go
  pkg/bussiness/kube-resources/alpha1/persistentvolumeclaim/multi_cluster_persistentvolumeclaim.go
  pkg/bussiness/kube-resources/alpha1/persistentvolumeclaim/persistentvolumeclaim.go
  pkg/bussiness/kube-resources/alpha1/pod/multi_cluster_pod.go
  pkg/bussiness/kube-resources/alpha1/resource/resource.go
  pkg/bussiness/kube-resources/alpha1/role/multi_cluster_role.go
  pkg/bussiness/kube-resources/alpha1/rolebinding/multi_cluster_rolebinding.go
  pkg/bussiness/kube-resources/alpha1/secret/multi_cluster_secret.go
  pkg/bussiness/kube-resources/alpha1/service/multi_cluster_service.go
  pkg/bussiness/kube-resources/alpha1/serviceaccount/multi_cluster_service.go
  pkg/bussiness/kube-resources/alpha1/statefulset/multi_cluster_statefulset.go
  pkg/bussiness/kube-resources/alpha1/storageclass/multi_cluster_storageclass.go
  pkg/bussiness/kube-resources/alpha1/utils.go
  pkg/server/filters/dispatch.go
  pkg/server/resources/alpha1/handler.go
  pkg/server/resources/alpha1/handlerTest.go
  pkg/server/resources/alpha1/register.go
  pkg/utils/clusterclient/clusterclient.go
Labels: enhancement, multi-cluster

#30 修改查询条件
  pkg/bussiness/kube-resources/alpha1/pod/multi_cluster_pod.go
  pkg/bussiness/kube-resources/alpha1/pod/pod.go
  pkg/server/apiserver.go
  pkg/unify/query/types.go
Labels: bugfix
